# Generated by Django 3.2.2 on 2021-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
